spring:

  profiles:
    active: dev

  jpa:
    database: MYSQL
    show_sql: true
    hibernate:
      ddl_auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
