spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://127.0.0.1:3306/blog



logging:
  level:
    root: warn
    com.ctfstar: info
  file:
    path: log/blog-pro.log
server:
  port: 8081